server:
  port: 8080

spring:

  application:
    name: gateway

  cloud:
    gateway:

      routes:

        - id: auth
          uri: http://auth:8080
          predicates:
            - Path=/auth/**

        - id: account
          uri: http://account:8080
          predicates:
            - Path=/account/**

        - id: espm
          uri: https://www.espm.br
          predicates:
            - Path=/espm/**