name: store-www

services:

  www:
    # image: nginx:latest
    build:
      dockerfile_inline: |
        FROM nginx:latest
        COPY ./app /usr/share/nginx/html
    ports:
      - 80:80
    # volumes:
    #   - ./app:/usr/share/nginx/html
